set t_ut=
set nocompatible              " be iMproved, required
filetype off                  " required


"FileType support
set filetype=on
filetype plugin on
filetype indent on

let g:completer_python_binary = '/usr/local/lib/python2.7/'
let g:completer_node_binary = 'usr/local/bin/node'


inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

packadd! dracula
syntax enable
colorscheme dracula

set incsearch


set ignorecase
set smartindent
set tabstop=4 
set shiftwidth=4 
set expandtab
set laststatus=2

set smartcase

"ctrlp stuff
set runtimepath^=~/.vim/pack/start/ctrlp.vim
set wildignore+=**/*.git,**/*.class,**/*.pyc,**/*.swp,**/*jar,**/*.zip
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 0
map <C-b> :CtrlPBuffer<CR>
map <C-d> :CtrlPDir<CR>
let g:ctrlp_extensions = [ 'dir','line']
let g:ctrlp_match_window = 'results:100'
let g:ctrlp_switch_buffer = 'et'
let g:ctrlp_max_depth = 4

if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

let g:ctrlp_use_caching = 0

" yaml indentation
au FileType yaml setlocal tabstop=2 expandtab shiftwidth=2 softtabstop=2

let g:auto_save = 1




filetype plugin indent on
syntax on

set winaltkeys=no

" validator config
let g:validator_javascript_checkers = ['jshint']
let g:validator_python_checkers = ['flake8']
let g:validator_permament_sign = 1


:set backspace=indent,eol,start

let g:rainbow_active = 1
let g:markdown_folding = 1 
let g:markdown_enable_folding = 1 

nmap <leader>d I<C-v>u2714 <ESC>
nmap <leader>x I<C-v>u2716 <ESC>

" Default to not read-only in vimdiff
set noro


nnoremap <leader>f :SideSearch<SPACE>

let g:vimwiki_list = [{'path': '~/Dropbox/notes', 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_ext2syntax = {'.md' : 'markdown'}

let g:vimwiki_markdown_link_ext = 1

set omnifunc=syntaxcomplete#Complete

nnoremap <leader>e :Explore <CR><SPACE>

set directory=$HOME/.vim/swapfiles//

" sidesearch root dir as current working dir
function! FindRootDirectory()
  return getcwd()
endfunction

" \ cd to change dir to working file
nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>

" camelcasemotion
"map <silent> w <Plug>CamelCaseMotion_w
"map <silent> b <Plug>CamelCaseMotion_b
"map <silent> e <Plug>CamelCaseMotion_e
"map <silent> ge <Plug>CamelCaseMotion_ge
"sunmap w
"sunmap b
"sunmap e
"sunmap ge

