# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color
export JIRA_API_TOKEN=EEdN5fJglsJ9dsJCjzIA8223
export ANDROID_HOME=/Users/russellstanley/Library/Android/sdk
export LD_LIBRARY_PATH=/usr/local/lib

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dracula"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(docker git)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
function gcm () {
   git commit -m "$*"
}
function pycharm() {
    ~/devtools/pycharm-community-4.0.4/bin/pycharm.sh $1
}

function take(){
    mkdir -p $1
    cd $1
}

function gitignore(){
    echo $1 >> .gitignore
}
function docker_kill_containers(){
    docker kill $(docker ps -aq)
}
function docker_rm_containers(){
    docker rm $(docker ps -aq)
}
function docker_rm_images(){
    docker rmi $(docker images -aq)
}
function docker_rm_volumes(){
    docker volume rm $(docker volume ls -q)
}
function docker_purge(){
    docker_kill_containers
    docker_rm_containers
    docker_rm_images
    docker_rm_volumes
}

function groot(){
    cd $(git rev-parse --show-toplevel)
}
function del(){
    mv $1 ~/deleted
}
function restore(){
    mv  ~/deleted/$1 $1
}


alias rawcurl="curl -iv --raw"
alias horn="mplayer ~/Dropbox/air_horn.mp3"
alias gs="git status"
alias ga="git add . && git add -u"
alias gdt="git difftool -y"
alias gdts="git difftool --staged -y"
alias showorig='find . -type f -name "*.orig"'
alias purgeorig='find . -type f -name "*.orig" -delete'
alias gtd='cd ~/Dropbox/system'
alias worklog='vim ~/Dropbox/system/work.log.md'
alias gud='git branch -f dev origin/dev && git fetch origin dev:dev -u && git remote prune origin && git-clean-branches' 
alias git-clean-branches='git branch --merged| egrep -v "(^\*|prod|dev)" | xargs -r git branch -d'
alias gpr="gh pr create --base dev --repo wavemm/monorepo --web" 
alias gprt="make m.typecheck && gpr" 
alias todo="vim ~/Dropbox/todo.md"
alias worklog="vim ~/Dropbox/worklog.md"
alias repo="cd /home/russell/code/monorepo"
alias wip="gcm russell wip"
alias tc="dmypy run ."
alias terraform_target_plan="terraform plan | grep 'updated\|created\|destroyed'"







# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

