# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="muse"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(fabric docker gradle)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
function gcm () {
   git commit -m "$*"
}
function gvopen() {
    gvim $($*)
}
function rassh () {
  ssh -i ~/.ssh/keys/ra_id_rsa ubuntu@$1
}
function racd(){
    cd ~/projects/radioactive/$1
}
function rascp () {
    scp -i ~/.ssh/keys/ra_id_rsa ubuntu@$*
}
function ramplayer() {
  token=$(ra_streamtoken)
  mplayer "$1?authtoken=$token"
}
function take(){
    mkdir -p $1
    cd $1
}

function gitignore(){
    echo $1 >> .gitignore
}
function rap(){
    if [ "$#" -eq 0 ]; 
    then 
        cd ~/projects/radioactive
    else 
        cd ~/projects/radioactive/$1
    fi
}
function docker_kill_containers(){
    docker kill $(docker ps -aq)
}
function docker_rm_containers(){
    docker rm $(docker ps -aq)
}
function docker_rm_images(){
    docker rmi $(docker images -aq)
}
function docker_rm_volumes(){
    docker volume rm $(docker volume ls -q)
}
function docker_purge(){
    docker_kill_containers
    docker_rm_containers
    docker_rm_images
    docker_rm_volumes
}

function groot(){
    cd $(git rev-parse --show-toplevel)
}

alias emc="emacsclient -t"
alias em="emacs -nw"
alias dualscreen="~/.screenlayout/dual_screen.sh"
alias singlescreen="~/.screenlayout/single_screen.sh"
alias adb=~/Android/Sdk/platform-tools/adb
alias suadb="sudo ~/Android/Sdk/platform-tools/adb"
alias gradle=./gradlew
alias proj="cd ~/projects"
alias android="~/Android/Sdk/tools/android"
alias rawcurl="curl -iv --raw"
alias horn="mplayer ~/Dropbox/air_horn.mp3"
alias gv="gvim"
alias gitpoa="git push origin --all"
alias gs="git status"
alias ga="git add . && git add -u"
alias gpull="git pull --all"
alias gpush="git push --all"


export ANSIBLE_CACHE_MAX_AGE=999999999
